# Site settings
title: deadsoftie
description: "The journal of deadsoftie"
url: "deadsoftie.com"

# Google Analytics
google_analytics: G-1853J298C9

# Author
author:
  name: Rahul Nair

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]
